#!/bin/sh

if [ "$(id -u)" -ne "0" ]; then
    echo "Please run as root"
    exit 1
fi

nocolor="\033[0m"

red="\033[0;31m"
green="\033[0;32m"
orange="\033[0;33m"
cyan="\033[0;36m"

color=""
if [ -t 1 ]; then
    color="true"
fi

rc_all=$(rcctl ls all)
rc_enabled=$(rcctl ls on)
rc_started=$(rcctl ls started)
rc_failed=$(rcctl ls failed)

list_started=""
list_forced=""
list_enabled=""
list_failed=""

for started in $rc_started; do
    for enabled in $rc_enabled; do
        if [ "$enabled" == "$started" ]; then
            list_started="$list_started $started"
            continue 2
        fi
    done
    list_forced="$list_forced $started"
done

for enabled in $rc_enabled; do
    for started in $rc_started; do
        if [ "$started" == "$enabled" ]; then
            continue 2
        fi
    done

    for failed in $rc_failed; do
        if [ "$failed" == "$enabled" ]; then
            list_failed="$list_failed $failed"
            continue 2
        fi
    done

    list_enabled="$list_enabled $enabled"
done

for service in $rc_all; do
    for forced in $list_forced; do
        if [ "$forced" == "$service" ]; then
            if [ "$color" = "true" ]; then
                echo "[${cyan}F${nocolor}] $service"
            else
                echo "[F] $service"
            fi
            continue 2
        fi
    done

    for started in $list_started; do
        if [ "$started" == "$service" ]; then
            if [ "$color" = "true" ]; then
                echo "[${green}+${nocolor}] $service"
            else
                echo "[+] $service"
            fi
            continue 2
        fi
    done

    for failed in $list_failed; do
        if [ "$failed" == "$service" ]; then
            if [ "$color" = "true" ]; then
                echo "[${red}D${nocolor}] $service"
            else
                echo "[D] $service"
            fi
            continue 2
        fi
    done

    for enabled in $list_enabled; do
        if [ "$enabled" == "$service" ]; then
            if [ "$color" = "true" ]; then
                echo "[${orange}-${nocolor}] $service"
            else
                echo "[-] $service"
            fi
            continue 2
        fi
    done

    echo "[ ] $service"
done
